[helpers]

[editorconfig.files]
editorconfig = "~/.editorconfig"

[homebrew]

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[zsh]
depends = ["starship"]

[zsh.files]
zprofile = { target = "~/.zprofile", type = "template" }
zshenv = "~/.zshenv"
zshrc = "~/.zshrc"
